version: '3.4'
services:
  grafana.avado.dappnode.eth:
    build: ./build
    image: 'grafana.avado.dappnode.eth:0.0.1'
    environment:
      - GF_SERVER_HTTP_PORT=3000
    restart: always
    volumes:
      - 'data:/var/lib/grafana'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '3333:3000/tcp'
volumes:
  data: {}
